rm(list = ls())
source("01_data_import.R")
source("02_radiocarbon_calibration.R")
source("03_proxy_processing_and_gam.R")
source("04_spd_analysis.R")
source("05_cross_correlation_analysis.R")
source("06_climate_settlement_gam.R")
source("07_random_forest_rolling_validation.R")
source("08_hidden_markov_modeling.R")
source("09_chronological_network_analysis.R")
source("10_spatiotemporal_mapping.R")
